### ISSUE TITLE
Use std::variant for DataContainer class.

### ISSUE THREAD

**Issue by IAmNotHanni** [inexorgame/entity-system#1]
* [x] Use a type safe union like [std::variant](https://en.cppreference.com/w/cpp/utility/variant) or [std::any](https://en.cppreference.com/w/cpp/utility/any) in inexor::entity_system::DataContainer class.

> This will replace the overhead of managing class members of different types as data containers.

* [x] Implement exception handling for type casting in inexor::entity_system::DataContainer.

**Comment by IAmNotHanni** [comment]
The ExperimentalDataContainer class will be discarded due to performances problems.
It's just so much slower than the DataContaner class.

![anycasttest](https://user-images.githubusercontent.com/7914428/43470665-68241226-94e9-11e8-86ec-e74ba467a29b.png)

The amound of memory saved by std::any is fully negligible compared with the performance loss!

**Comment by IAmNotHanni** [comment]
Assigned to @Fohlen.

**Comment by IAmNotHanni** [comment]
@Fohlen made the suggestion to use std::variant for now since its easier to use it saves us time.
We can work on improving the performance later on if neccesary.
@aschaeffer already pointed out that finding a good solution for multi type data containers is a long discussion because there is no perfect solution.

**Comment by IAmNotHanni** [comment]
Also we will remove unneccesary data types.
The entity-system should support the following data types for now:

* Integer
* Bool
* Float
* Double
* std::string

**Comment by IAmNotHanni** [comment]
I think we should create a pull request for your branch @Fohlen.

**Comment by Fohlen** [comment]
It has been decided that @aschaeffer and I will present two independent implementation's of `DataContainer` to decide for.
In the end we can then use both or the "better" one, we'll see.
It is important that both implementations provide a `DataContainer` class so that other people can work on other issues in the meantime.

Best would be if we finish drafts in January.
