### ISSUE TITLE
Implement entity system as an Inexor module.

### ISSUE THREAD

**Issue by IAmNotHanni** [inexorgame/entity-system#11]
**The entity system is a module of Inexor.**

As soon as @a-teammate, @aschaeffer and @Fohlen have found a way to build Inexor as a set of modules, we have to attach the entity system to it.

**Comment by IAmNotHanni** [comment]
https://github.com/inexorgame/modular-engine

**Comment by IAmNotHanni** [comment]
Hanack just told me he implemented the entity-system as a module using [boost DI](http://boost-experimental.github.io/di/).
[This](https://github.com/inexorgame/entity-system/commit/dd77d580b9ebea151d15b1b702186f5eb3a166b9) looks exciting!

**Comment by Fohlen** [comment]
Has been done nicely with the current source structure. Closing.
