### ISSUE TITLE
Think of a proper packaging mechanism

### ISSUE THREAD

**Issue by Fohlen** [inexorgame/entity-system#111]
Using the [downloader script](https://github.com/inexorgame/entity-system/blob/master/download_assets.py) is a quick fix as I already outlined. We should find a solution to do this properly as soon as possible. @MartinMuzatko and @movabo what is the current progress of Inexor cloud? Is there already some specification on how packages look? It would be good if we could write a little demo program that leverages the entity-API as a command line tool to do exactly this. This approach will have benefits

- it will force us to work cleanly and lay out a package structure for the future
- it will make use of the entity-system API as our first, non-standalone consumer (one that is not compiled with the entity-system itself)

This is also a good test on how far / how well our entity-system API performs.

**Comment by MartinMuzatko** [comment]
We have already defined a clear set of types of content and how to access them. Method as of now is HTTP.

Documentation will follow.

In short: you download entity based contents as json. Textures, models and sounds are served as binary.

We are using [strapi](https://strapi.io/documentation/3.x.x/guides/filters.html#available-operators) as the underlying content management framework/headless server/API mechanism.

Once the system is online, you can simply GET https://api.inexor.org/contents/1 if know the ID. This contains a link to the binary and other metadata (name, description etc)
You could also filter for starred content or have a content package.
Contents can be nested.. e.g. have a json field for dependencies. These can be recursively resolved via graphql, but have to investigate on this.

As said: docs are following soon :)

**Comment by IAmNotHanni** [comment]
This is no longer in the scope of this repository.
