### ISSUE TITLE
MonitorManager causes runtime error on MS Windows.

### ISSUE THREAD

**Issue by IAmNotHanni** [inexorgame/entity-system#115]
A runtime error was introduced in [this commit](https://github.com/inexorgame/entity-system/commit/594397d2fb4e08d09f96f4e2d7f96c7e34bdac25).
I get the following runtime error when trying to execute `entity-system-standalone`

![runtime_error_window_manager](https://user-images.githubusercontent.com/7914428/55889239-14ee2080-5bb1-11e9-9b13-a2d7f7946a80.jpg)

Console output: https://pastebin.com/genFBQt2

**Comment by IAmNotHanni** [comment]
The debugger tells me that some runtime errors are caused by this code part:

```
void WindowManager::init()
{
	log_manager->register_logger(LOGGER_NAME);

	create_window("Test 1", 0, 0, 300, 300);
	create_window("Test 2", 300, 0, 300, 300);
	create_window("Test 3", 0, 300, 300, 300);
	create_window("Test 4", 300, 300, 300, 300);
}
```

**Comment by IAmNotHanni** [comment]
It works when I debug the program step by step:

![concurrency_problem_with_window_manager](https://user-images.githubusercontent.com/7914428/55892744-2b977600-5bb7-11e9-8a29-dd4aee0f99fa.jpg)

**Comment by IAmNotHanni** [comment]
This is bad news actually, because I suppose there is a problem with the `thread-safety` of the code.

**Comment by aschaeffer** [comment]
git pull?

**Comment by IAmNotHanni** [comment]
Im up to date with remote.

**Comment by aschaeffer** [comment]
Hmm, I don't think it's thread-safety but errors during initialization of the OpenGL context:

```
GL::Context: cannot retrieve OpenGL version
...
no-layout-qualifiers-on-old-glslerror
...
GL::Renderer::Error::InvalidOperation
```

Please comment `loading_screen->init();` in RenderModule.cpp

**Comment by IAmNotHanni** [comment]
I had to comment out the following lines to get it working:
```
//loading_screen->init();
//triangle_example->init();
```

**Comment by aschaeffer** [comment]
Because you deactivated triangle_example?

**Comment by IAmNotHanni** [comment]
Yes I can't see the triangle because I commented it out but this does not fix this issue.

**Comment by aschaeffer** [comment]
Can we close this issue?

**Comment by IAmNotHanni** [comment]
Yes its done.
