### ISSUE TITLE
Use namespace std consistently in entity-system's core.

### ISSUE THREAD

**Issue by IAmNotHanni** [inexorgame/entity-system#117]
Add `using namespace std;` everywhere in the entity-system's core.

**Comment by IAmNotHanni** [comment]
Because we are not using the old cube2 engine code, there is for example no danger of mixing up `std::vector` with cube engine's `vector` class.

**Comment by aschaeffer** [comment]
[Don't ](https://www.geeksforgeeks.org/using-namespace-std-considered-bad-practice/):-)

Generally "using namespace" is considered as bad practise:

* Scoping issues / name conflicts
* Compile time increases
* Harder to find errors

Better approaches are:

* Define shortcuts only for what you are really using: `using shared_ptr = std::shared_ptr;`
* Define shortcuts in cpp file, if the shortcut is only needed in cpp but not in hpp
* For shortcuts in hpp files:
    * Define shortcuts within class scope
    * If not possible, define shortcuts in namespace scope `namespace inexor { namespace {xxx`
