### ISSUE TITLE
Add the current thread ID to every spdlog output.

### ISSUE THREAD

**Issue by IAmNotHanni** [inexorgame/entity-system#119]
Since we already have multiple threads running in Inexor's entity system, we should add the ID of the current thread to every spdlog output. We can use `std::this_thread::get_id()` for this. We somehow need to customise the logger output in spdlog for this.

**Comment by IAmNotHanni** [comment]
https://en.cppreference.com/w/cpp/thread/get_id

**Comment by gabime** [comment]
@IAmNotHanni you can just use the %t flag in the log pattern (https://github.com/gabime/spdlog/wiki/3.-Custom-formatting)

**Comment by IAmNotHanni** [comment]
Thank you very much!

**Comment by aschaeffer** [comment]
2fcff2d209040ed203de6ccf27a30b072899bcff

**Comment by santoshba** [comment]
> https://en.cppreference.com/w/cpp/thread/get_id

Hi,
Do you have a sample usage for spdlog that emits the thread_id ?

**Comment by IAmNotHanni** [comment]
The problem is that std::this_thread::get_id is of type ostream. Output with spdlog directly is not possible. You could convert it to uint32_t though using sstream:

```
auto thread_id = std::this_thread::get_id();
std::stringstream thread_id_converter;
thread_id_converter << std::this_thread::get_id();
uint64_t id = static_cast<uint64_t>(std::stoull(thread_id_converter.str()));
```

**Comment by IAmNotHanni** [comment]
On the other hand, you can use %T to print the current thread in spdlog.
