### ISSUE TITLE
tbb_debug.dll is missing in the build directory.

### ISSUE THREAD

**Issue by IAmNotHanni** [inexorgame/entity-system#121]
When I compile and start `inexor-entity-system-standalone` I get the following error message:

![tbb_debug_dll_file_missing](https://user-images.githubusercontent.com/7914428/56095233-da4ef580-5eda-11e9-9473-0e0128081f14.jpg)

I must copy `tbb_debug.dll` manually into the build folder to make the program start correctly.
Why is that? Is there something wrong with the configuration of the project?

**Comment by IAmNotHanni** [comment]
A little info about Intel TBB:

> Threading Building Blocks (TBB) lets you easily write parallel C++ programs that take full advantage of multicore performance, that are portable and composable, and that have future-proof scalability.

See: https://www.threadingbuildingblocks.org/

**Comment by IAmNotHanni** [comment]
When I copy `tbb_debug.dll` into the build folder the program can start. This only is a quick fix though.

**Comment by a-teammate** [comment]
conan can import stuff to a directory when we use an [imports] section. (dunno if thats possible easily with a conanfile.txt, but its straight forward with a conanfile.py)
then there has to be a CMAKE_BINARY_PATH or sth like this set in the cmakelists.
it was already done in inexor-core's cmake setup

**Comment by IAmNotHanni** [comment]
This issue does not occur anymore when using Visual Studio 2017 with the new `conanfile.py`.
The issue can therefore be closed.
