### ISSUE TITLE
Simplify data types in the entity system.

### ISSUE THREAD

**Issue by IAmNotHanni** [inexorgame/entity-system#25]
We don't really need `double` as a type in game programming.
We also do not need big integers (std::int64).
This results in the following data type enumeration:

```
enum ENTSYS_DATA_TYPE
{
   ENTSYS_DATA_TYPE_UNDEFINED = 0,
   ENTSYS_DATA_TYPE_INT,
   ENTSYS_DATA_TYPE_FLOAT,
   ENTSYS_DATA_TYPE_STRING,
   ENTSYS_DATA_TYPE_BOOL,
};

```

**Comment by IAmNotHanni** [comment]
On the other hand we don't know if we some day need this data type so why not keep it.

**Comment by a-teammate** [comment]
Double may also be needed, because sometimes you require additional precision (e.g. for positions)
