### ISSUE TITLE
Create a Conanfile.txt and add all dependencies of the entity-system.

### ISSUE THREAD

**Issue by IAmNotHanni** [inexorgame/entity-system#32]
It's not a good practise to add all current dependencies manually to the 'dependencies' folders. Let's use [Conan Package Manager](https://conan.io/) for this as usual in Inexor.

The following dependencies need to be downloaded and added to the 'dependencies' folder by conan when running the conan file:

| Dependency | Version | Explanation | License |
| -------------- | --------- | -------------- |-------------- |
| [gtest](https://github.com/abseil/googletest) | v1.8.1 | Google Testing Framework | BSD 3-Clause |
| [crossguid](https://github.com/graeme-hill/crossguid) | v0.2.2 | [UUID](https://en.wikipedia.org/wiki/Universally_unique_identifier) generator | MIT |
| [glm](https://glm.g-truc.net/0.9.9/index.html) | 0.9.9.3 | OpenGL Mathmatics | MIT |
| [hayai](https://github.com/nickbruun/hayai) | v1.0.2  | C++ Benchmarking Framework | zlib |
| [JSON](https://github.com/nlohmann/json) | 3.4.0 | JSON library | MIT |

**Comment by IAmNotHanni** [comment]
Maybe we should use [stduuid](https://github.com/mariusbancila/stduuid) instead of boost uuid since it's licensed under MIT license.

**Comment by Croydon** [comment]
> Maybe we should use stduuid instead of boost uuid since it's licensed under MIT license.

Both licenses are fine.

**Comment by IAmNotHanni** [comment]
I added a [JSON library](https://github.com/nlohmann/json).

**Comment by IAmNotHanni** [comment]
For now I added stduuid manually in the dependency folder.

**Comment by IAmNotHanni** [comment]
Everything has been added to the conanfile except of hayai. Since we don't need hayai at the moment we can close this issue for now.
