### ISSUE TITLE
Update README and wiki pages.

### ISSUE THREAD

**Issue by IAmNotHanni** [inexorgame/entity-system#41]
Update the readme file:

* [x] Update README file.

Incorporate the following points into the wiki:

**Definitions**:
* [ ] What is a type ?
* [ ] What is an entity ?
* [ ] What is an attribute ?
* [ ] What is a relation ?
* [ ] What is an instance ?

**Architecture**:
* [ ] Why do we use std::shared_ptr ?
* [ ] Which namespaces are used ?
* [ ] Which multithreading strategy will be used ?
* [ ] Why is a DataContainer class used ?
* [ ] Which components does the class EntitySystem have ?
* [ ] Why are both instantes and types stored ?
* [ ] How does error handling in the entity-system work ?
* [ ] How do manager classes work (add/delete/get/modify) ?
* [ ] How does importing and exporting of the entity-system work ?

**Project**:
* [ ] How to get involved ?
* [ ] How to build the code ?
* [ ] How do you document the code ?
* [ ] What are the goals of developing this entity-system ?
* [ ] Which systems are going to be based in this entity system ?

**Comment by IAmNotHanni** [comment]
@Fohlen Yes.

**Comment by Fohlen** [comment]
I have moved all the contents of the wiki to the site. See https://github.com/inexorgame/site/pull/46

**Comment by Fohlen** [comment]
This has been done with 2060882af05b3a4382f7cd27be0ac44a11d713f0
