### ISSUE TITLE
Use graph library to manage entities

### ISSUE THREAD

**Issue by Fohlen** [inexorgame/entity-system#52]
@a-teammate suggested a good [graph](https://github.com/cbbowen/graph) library that is header only C++17.
This library should be used to implement entities on top of it:

- EntityManager creates Node's
- RelationManager creates Edge's
- "Attribute"'s are translated into properties of the property graph map
- EntitySystem is a adjacency list that handles queries (iteration)

This has the following benefits

- almost zero implementation cost
- only interface to a graph system must be added
- using a rock solid graph computation system that is compatible to STL, thus fast, space efficient and thread safe by default

**Comment by a-teammate** [comment]
close as not viable atm?

**Comment by Fohlen** [comment]
We should evaluate this again when we want to traverse the entity system

**Comment by Fohlen** [comment]
I have had a talk with the author of proposed library, and apparently support for MSVC (specifically for some C++20a features) will not be covered any time soon. Closing as irrelevant until we hit actual performance problems iterating the entity system.
