### ISSUE TITLE
Use std::optional instead of returning null pointers or error codes

### ISSUE THREAD

**Issue by aschaeffer** [inexorgame/entity-system#62]
This will make the Entity System API rock solid:

* https://en.cppreference.com/w/cpp/utility/optional
* https://www.bfilipek.com/2018/05/using-optional.html

**Comment by Fohlen** [comment]
Shouldn't we use some logging / error propagation lib which surely has solved this before oO?

**Comment by IAmNotHanni** [comment]
Why use a lib when you can use C++17 standard?
Done: https://github.com/inexorgame/entity-system/commit/4cbad62ebb303b332651334e18529451410d140f.
