### ISSUE TITLE
Add Travis build setup

### ISSUE THREAD

**Issue by Fohlen** [inexorgame/entity-system#69]
This task includes multiple things

- [x] add linux + GCC 7
- [x] add linux + Clang 8
- [x] add OSX with latest stable clang
- [ ] add Windows with VS Studio latest

**Comment by aschaeffer** [comment]
In order to support windows:

* https://docs.travis-ci.com/user/reference/windows/
* https://chocolatey.org/packages/conan

> Take note that our Windows environment is in early stages and a minimal subset of what’s available on Linux or macOS is currently supported.

**Comment by Fohlen** [comment]
You could also use GitHub actions, which supports Windows, Linux and OSX out of the box just fine. See https://help.github.com/en/articles/virtual-environments-for-github-actions

**Comment by IAmNotHanni** [comment]
This will be replaced with Github actions.
