### ISSUE TITLE
Integrate dependency injection framework

### ISSUE THREAD

**Issue by aschaeffer** [inexorgame/entity-system#72]
* Boost.DI

**Comment by IAmNotHanni** [comment]
Related: https://github.com/inexorgame/entity-system/issues/11

**Comment by aschaeffer** [comment]
Done.

- [x] Added Boost.DI dependency
- [x] The entire entity system uses dependency injection (using constructor injection)
- [x] No runtime performance overhead
- [x] Works on linux and windows
