### ISSUE TITLE
Handle lifecycle accordingly

### ISSUE THREAD

**Issue by Fohlen** [inexorgame/entity-system#79]
Maybe we can use a library for this too. We've had the problem a *lot* of times that Inexor won't properly shut down. Investigate, fix, make it awesome.

**Comment by aschaeffer** [comment]
Currently the problem is the integration of the rest server

**Comment by Fohlen** [comment]
This includes mainly a strategy for thread pooling and signalling @a-teammate

**Comment by Fohlen** [comment]
I believe @a-teammate and I solved this in a hacking session in Stuttgart. Closing.
